### ISSUE TITLE
Fails to start on Ubuntu

### ISSUE THREAD

**Issue by CreativeCactus** [jmosbech/mail-null#13]
/usr/bin/env: ‘node\r’: No such file or directory.

**Comment by CreativeCactus** [comment]
Seems to be caused by DOS format of `bin/mail-null` which ends up at `/usr/local/bin/mail-null` or `which mail-null` for me.

**Comment by CreativeCactus** [comment]
Fixed and I get 
```
SMTP server listening on port 2525                                                                                                                                                                                                                                                   
Web server listening on port 3000 (development)                                                                                                                                                                                                                                      
events.js:163                                                                                                                                                                                                                                                                        
      throw er; // Unhandled 'error' event                                                                                                                                                                                                                                           
      ^                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                     
Error: watch /usr/local/lib/node_modules/mail-null/package.json ENOSPC                                                                                                                                                                                                               
    at exports._errnoException (util.js:1029:11)                                                                                                                                                                                                                                     
    at FSWatcher.start (fs.js:1399:19)                                                                                                                                                                                                                                               
    at Object.fs.watch (fs.js:1425:11)                                                                                                                                                                                                                                               
    at createFsWatchInstance (/usr/local/lib/node_modules/mail-null/node_modules/chokidar/lib/nodefs-handler.js:37:15)                                                                                                                                                               
    at setFsWatchListener (/usr/local/lib/node_modules/mail-null/node_modules/chokidar/lib/nodefs-handler.js:80:15)                                                                                                                                                                  
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/mail-null/node_modules/chokidar/lib/nodefs-handler.js:228:14)                                                                                                                                           
    at FSWatcher.NodeFsHandler._handleFile (/usr/local/lib/node_modules/mail-null/node_modules/chokidar/lib/nodefs-handler.js:255:21)                                                                                                                                                
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/mail-null/node_modules/chokidar/lib/nodefs-handler.js:473:21)                                                                                                                                                              
    at FSReqWrap.oncomplete (fs.js:114:15) 
```

So I assume this goes further.

**Comment by jmosbech** [comment]
The first part of the problem should have been fixed a long time ago by 5f8cd55

Are you running the latest version?

The second part of the issue will require a little more digging.
